### ISSUE TITLE
Change the  size of gif generated

### ISSUE THREAD

**Issue by utkarsh-tyagi** [CompVis/image2video-synthesis-using-cINNs#4]
Hi Team,

Thanks for the outstanding work!

Is it possible to change the size of the gif to (640,640) as I can see that the quality of the gif is very poor (128,128)?

Any idea?

**Comment by mdorkenw** [comment]
Hi 

Thanks for your interest! 

One could upsample the images before creating the gif file using an upsampling function of your liking e.g. bilinear. However, I do not expect the quality to improve as our model generates samples mostly on 128er resolution. Other works employed some sort of upsampling/high res network for generating videos in higher resolution. 

I hope this response answers your question which is why I am closing this issue. Feel free to comment again if that's not the case.

**Comment by darkzbaron** [comment]
Yeah shame, any update on that?
