### ISSUE TITLE
image size 128

### ISSUE THREAD

**Issue by Li-En-Good** [CompVis/image2video-synthesis-using-cINNs#6]
Hi,

I noticed that the images were reshaped to to 128*128 pixels.
Is there a specific reason for this? Why not use sub-sampling instead? 
Would I be able to use a larger size for training?
Thanks a lot!

**Comment by mdorkenw** [comment]
Hi! 

Thanks for your interest in this work. The images are resized to the image size for which the model was trained which is set in the config (model.config.Data['img_size']). For resizing kornia.resize was used which uses by default bilinear resampling as far as I know. 

It is theoretically possible to train on larger image sizes e.g. 256. However, one needs extremely large GPU memory due to the adversarial losses. A better solution, which was also done in [DeepLandscape](https://github.com/advimman/deep-landscape), is to train a separate network just for upsampling on an image level.
