### ISSUE TITLE
Retrain the entire model on other dataset

### ISSUE THREAD

**Issue by msm11** [CompVis/image2video-synthesis-using-cINNs#7]
Hello, i think your work very interesting

while reading this paper, i got some question

if i retrain the entire model or fine-tune some part of model on other dataset, with larger domain than the one used in this paper, it could predict video sequences well?

for examples, if retrain entire model on new DTDB dataset including all four textures, it could predict well? (just in terms of qualitative result)

**Comment by mdorkenw** [comment]
Hello, thanks for your interest! 

We trained a separate model for each DTDB texture (fire, waterfall, etc.) as the dynamics of each is unique and the **dataset size for each of them was small.** Because of that, generalization to other textures will be limited, and training one model for all textures hasn't worked well when I recall correctly. In general, it _should_ be possible to train this model on a sufficiently large dataset for multiple textures. I haven't explored fine-tuning this model to other textures or datasets which is why I can't provide any help with that. 

Given the enormous progress in the area of generative modeling, the used architecture is by now outdated. With models and architectures like [MAGVit](https://github.com/google-research/magvit) this should be easily possible.

**Comment by msm11** [comment]
thank you for your detailed and kind answer!
